server:
  error:
    include-message: always
  port: 8081

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        web.cors: DEBUG

db:
  host: localhost
  port: 5432
  databaseName: ems-api-db

spring:
  application:
    name: ems-api-spring
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.databaseName}
    username: ems-api-db-user
    password: ems-api-db-pwd
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

allowed-origins:
  http://localhost:5173,
  http://localhost:8080,
  http://localhost:4200

jwt:
  secret: '6653572f85a0378b9704f0f226ab09cf0f741918cc8371635baefb56ef0589f7'
